### ISSUE TITLE
resize video youtube

### ISSUE THREAD

**Issue by giselebrugger** [h5p/h5p-image-hotspot-question#10]
Hello
When I add a YouTube video as a hotspot I can not resize the video. Is it possible to change this setting even if it is via css?
Because I always have to leave the background image very large or the video stays with a scroll

**Comment by fnoks** [comment]
I'll close this one, since it seems to be placed on the wrong github repo, and the same question is duplicated in h5p-image-hotspots. Please reopen if I am mistaken
