### ISSUE TITLE
Not possible to add a href links to the feedback text

### ISSUE THREAD

**Issue by jannesarkela** [h5p/h5p-image-hotspot-question#4]
Hi,

currently it's not possible to add a href links to the feedback text (the code shows as text in the final output). We have customers who would like to have the option, in order to create more fluid course flow. 

Allowing it in code is sufficient; 

`<a href="">link</a>`

**Comment by fnoks** [comment]
Hi,

To be able to do this, the feedback text would need to use the html widget. That could be done by altering the semantics using a hook on the specific site, or by creating a pull request.

**Comment by jannesarkela** [comment]
Ah yes of course - now that I read about the semantics config it's all clear. Thank you!

**Comment by fnoks** [comment]
You're welcome :)
